export const COOKIE_REFRESH_TOKEN = "ES-APPLICATION-AUTHENTICATION";
export const ENCRY_KEY = process.env.REACT_APP_ENCRY_KEY ? process.env.REACT_APP_ENCRY_KEY : "ENCRY_KEY";
export const SESSION_STORAGE_USER_KEY = "ES-USER-INFOMATION";
export const SESSION_STORAGE_ACCESS_TOKEN_KEY = "ES-ACCESS-TOKEN-KEY";
export const SESSION_STORAGE_ACCESS_TOKEN_EXPIREDATE_KEY = "ES-ACCESS-TOKEN-EXPIREDATE";